import { Theme } from './types';

export const THEMES: Theme[] = [
  {
    id: 'slate',
    name: 'Slate',
    properties: {
      '--color-primary': '#0f172a',
      '--color-secondary': '#1e293b',
      '--color-tertiary': '#334155',
      '--color-accent': '#38bdf8',
      '--color-accent-hover': '#0ea5e9',
      '--color-accent-2': '#22d3ee',
      '--color-accent-3': '#2dd4bf',
      '--color-text-base': '#e2e8f0',
      '--color-text-muted': '#94a3b8',
      '--color-text-inverted': '#0f172a',
      '--color-border-color': '#334155',
      '--color-danger-bg': 'rgba(225, 29, 72, 0.2)',
      '--color-danger-border': '#be123c',
      '--color-danger-text': '#fda4af',
      '--font-sans': "'Inter', sans-serif",
      '--font-serif': "'Lora', serif",
      '--font-mono': "'Roboto Mono', monospace",
    },
  },
  {
    id: 'cyberpunk',
    name: 'Cyberpunk',
    properties: {
      '--color-primary': '#0d0221',
      '--color-secondary': '#241b3a',
      '--color-tertiary': '#3c2f5a',
      '--color-accent': '#ff00ff',
      '--color-accent-hover': '#c700c7',
      '--color-accent-2': '#00f5d4',
      '--color-accent-3': '#f7f531',
      '--color-text-base': '#e6e6e6',
      '--color-text-muted': '#a6a6a6',
      '--color-text-inverted': '#0d0221',
      '--color-border-color': '#3c2f5a',
      '--color-danger-bg': 'rgba(255, 0, 93, 0.2)',
      '--color-danger-border': '#ff005d',
      '--color-danger-text': '#ff6b9a',
      '--font-sans': "'Roboto Mono', monospace",
      '--font-serif': "'Roboto Mono', monospace",
      '--font-mono': "'Roboto Mono', monospace",
    },
  },
  {
    id: 'parchment',
    name: 'Parchment',
    properties: {
      '--color-primary': '#fdf6e3',
      '--color-secondary': '#f8f0d5',
      '--color-tertiary': '#ede4c7',
      '--color-accent': '#d33682',
      '--color-accent-hover': '#b32d6d',
      '--color-accent-2': '#268bd2',
      '--color-accent-3': '#859900',
      '--color-text-base': '#586e75',
      '--color-text-muted': '#839496',
      '--color-text-inverted': '#fdf6e3',
      '--color-border-color': '#eee8d5',
      '--color-danger-bg': 'rgba(220, 50, 47, 0.1)',
      '--color-danger-border': '#dc322f',
      '--color-danger-text': '#dc322f',
      '--font-sans': "'Lora', serif",
      '--font-serif': "'Playfair Display', serif",
      '--font-mono': "'Roboto Mono', monospace",
    },
  },
  {
    id: 'forest',
    name: 'Forest',
    properties: {
      '--color-primary': '#1a2e2a',
      '--color-secondary': '#2b4942',
      '--color-tertiary': '#3c645a',
      '--color-accent': '#a3e635', /* lime-400 */
      '--color-accent-hover': '#84cc16', /* lime-500 */
      '--color-accent-2': '#facc15', /* yellow-400 */
      '--color-accent-3': '#fb923c', /* orange-400 */
      '--color-text-base': '#e0e6e5',
      '--color-text-muted': '#a7b1af',
      '--color-text-inverted': '#1a2e2a',
      '--color-border-color': '#3c645a',
      '--color-danger-bg': 'rgba(249, 115, 22, 0.2)',
      '--color-danger-border': '#f97316',
      '--color-danger-text': '#fb923c',
      '--font-sans': "'Inter', sans-serif",
      '--font-serif': "'Lora', serif",
      '--font-mono': "'Roboto Mono', monospace",
    },
  },
];